version: "3"

services:
  postgres:
    image: postgres:15.3
    container_name: darunia-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - darunia-postgres:/data/postgres
    ports:
      - "5433:5432"

volumes:
  darunia-postgres:
